name: flutter_seguridad_en_casa
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  app_links: ^6.1.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0
  rive: ^0.13.12  
  path: ^1.9.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  sqflite: ^2.3.3+1
  uuid: ^4.4.0
  hive_flutter: ^1.1.0
  http: ^1.2.2
  web_socket_channel: 3.0.3
  multicast_dns: ^0.3.2
  connectivity_plus: ^6.0.3
  wifi_iot: ^0.3.19
  permission_handler: ^11.3.1
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/rive/camara.riv  
    - assets/rive/registro.riv
    - assets/rive/cargando.riv
