// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlNtphs3hNtYbs48OG9xUdJGLhphedATc',
    appId: '1:83865748193:web:e8e3972532c7def567ada0',
    messagingSenderId: '83865748193',
    projectId: 'casasegura-3ed50',
    authDomain: 'casasegura-3ed50.firebaseapp.com',
    storageBucket: 'casasegura-3ed50.firebasestorage.app',
    measurementId: 'G-YPLJZNTYN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-VMidSp5x_wNIUNjzsCwqlcl5bJ0y7qc',
    appId: '1:83865748193:android:740ea8c673b50cfc67ada0',
    messagingSenderId: '83865748193',
    projectId: 'casasegura-3ed50',
    storageBucket: 'casasegura-3ed50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZzUMroqeMYFwT1gj9a5x7dBjrDIi1PmY',
    appId: '1:83865748193:ios:d8b1b747162fd8ae67ada0',
    messagingSenderId: '83865748193',
    projectId: 'casasegura-3ed50',
    storageBucket: 'casasegura-3ed50.firebasestorage.app',
    iosBundleId: 'com.example.flutterSeguridadEnCasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZzUMroqeMYFwT1gj9a5x7dBjrDIi1PmY',
    appId: '1:83865748193:ios:d8b1b747162fd8ae67ada0',
    messagingSenderId: '83865748193',
    projectId: 'casasegura-3ed50',
    storageBucket: 'casasegura-3ed50.firebasestorage.app',
    iosBundleId: 'com.example.flutterSeguridadEnCasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlNtphs3hNtYbs48OG9xUdJGLhphedATc',
    appId: '1:83865748193:web:180c51a9a40429d067ada0',
    messagingSenderId: '83865748193',
    projectId: 'casasegura-3ed50',
    authDomain: 'casasegura-3ed50.firebaseapp.com',
    storageBucket: 'casasegura-3ed50.firebasestorage.app',
    measurementId: 'G-M86ZDV0W3J',
  );
}
